### ISSUE TITLE
为什么要注释掉 waitUntil: 'networkidle0'

### ISSUE THREAD

**Issue by jymsy** [zuoyanart/sparender#1]
https://github.com/zuoyanart/sparender/blob/668e5daba6c4f421db58aff69151ef9bb74b5edc/src/service/render.js#L120

注释掉的话会不会有些js没执行完就返回页面了？

**Comment by zuoyanart** [comment]
会增加等待时间

**Comment by zuoyanart** [comment]
目前还没遇到你说的这种情况，现在做的是xhr执行完毕
